const fs = require('fs');
const path = require('path');
const { GoogleGenerativeAI } = require('@google/generative-ai');
require('dotenv').config({ path: '../.env' });

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function generate() {
    console.log("Generating comprehensive states data with Gemini...");

    const prompt = `Generate a valid JSON array of objects representing ALL 28 states of India. 
For each state, include a top-quality Unsplash image URL for 'heroImage' and 'thumbnail', a catchy 'tagline', and an array of at least 10 major 'cities' (not just strings, but objects with { name, tagline, image }). 
Images MUST be from Unsplash (e.g. https://images.unsplash.com/photo-XXX).
Format:
[
  { 
    "id": "rajasthan", "name": "Rajasthan", "tagTitle": "ROYAL RAJASTHAN", "tagline": "Land of Kings", 
    "thumbnail": "...", "heroImage": "...", "isPopular": true,
    "cities": [
      { "name": "Jaipur", "tagline": "Pink City", "image": "..." },
      ...10+ cities
    ]
  },
  ...all 28 states
]

Return strictly the JSON array, no markdown wrappers, no formatting, just pure JSON string ready to be parsed.`;

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const result = await model.generateContent(prompt);
    
    let text = result.response.text();
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();

    const newJsContent = `// Auto-generated by AI
const U = 'https://images.unsplash.com/';

export const heroSlides = [
  { id: 'slide-1', title: 'Serene Kerala Backwaters', subtitle: 'Experience tranquility in God\\'s Own Country',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=2070&auto=format&fit=crop', stateId: 'kerala' },
  { id: 'slide-2', title: 'Majestic Taj Mahal', subtitle: 'Witness the eternal monument of love',
    image: 'https://images.unsplash.com/photo-1564507592208-0282ee0a90af?w=2070&auto=format&fit=crop', stateId: 'uttar_pradesh' },
  { id: 'slide-3', title: 'Royal Rajasthan Forts', subtitle: 'Dive into the history of the Land of Kings',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=2070&auto=format&fit=crop', stateId: 'rajasthan' }
];

export const statesData = ${text};
`;

    const outputPath = path.join(__dirname, '../../client/src/data/statesData.js');
    fs.writeFileSync(outputPath, newJsContent);
    console.log("Successfully wrote all 28 states and their 10+ cities to statesData.js");
}

generate().catch(console.error);
